// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJj6fKBY5vwj-8Ot8nr5ZckvUFV0m-pg',
    appId: '1:871678023262:web:458524f8b0c713d69a06cf',
    messagingSenderId: '871678023262',
    projectId: 'proyectomoviles2-ee2fa',
    authDomain: 'proyectomoviles2-ee2fa.firebaseapp.com',
    storageBucket: 'proyectomoviles2-ee2fa.firebasestorage.app',
    measurementId: 'G-P8M66KQM33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygb3Q6WW8ZOo5mW5IfXzQnse8ExQHGtg',
    appId: '1:871678023262:android:adf1bcb2249277189a06cf',
    messagingSenderId: '871678023262',
    projectId: 'proyectomoviles2-ee2fa',
    storageBucket: 'proyectomoviles2-ee2fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKC5zG3kXwskFWcoOtYX2-uOtF3CBoQAA',
    appId: '1:871678023262:ios:3009d934de027fb19a06cf',
    messagingSenderId: '871678023262',
    projectId: 'proyectomoviles2-ee2fa',
    storageBucket: 'proyectomoviles2-ee2fa.firebasestorage.app',
    iosBundleId: 'com.example.proyectomovilesii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKC5zG3kXwskFWcoOtYX2-uOtF3CBoQAA',
    appId: '1:871678023262:ios:3009d934de027fb19a06cf',
    messagingSenderId: '871678023262',
    projectId: 'proyectomoviles2-ee2fa',
    storageBucket: 'proyectomoviles2-ee2fa.firebasestorage.app',
    iosBundleId: 'com.example.proyectomovilesii',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJj6fKBY5vwj-8Ot8nr5ZckvUFV0m-pg',
    appId: '1:871678023262:web:2e47c928d92cb3dd9a06cf',
    messagingSenderId: '871678023262',
    projectId: 'proyectomoviles2-ee2fa',
    authDomain: 'proyectomoviles2-ee2fa.firebaseapp.com',
    storageBucket: 'proyectomoviles2-ee2fa.firebasestorage.app',
    measurementId: 'G-70X1GYJVN2',
  );

}